### ISSUE TITLE
ValueError: Could not find a backend to open `G:\GitFork\AnimateDiff\samples\Gradio-2023-08-08T20-17-31\sample\0.mp4`` with iomode `wI`.

### ISSUE THREAD

**Issue by KaiJia2017** [guoyww/AnimateDiff#110]
Based on the extension, the following plugins might add capable backends:
  FFMPEG:  pip install imageio[ffmpeg]
  pyav:  pip install imageio[pyav]
  4%|███▎                                                                               | 1/25 [00:01<00:28,  1.19s/  8%|██████▋                                                                            | 2/25 [00:02<00:27,  1.1 12%|█████████▉                                                                         | 3/25 [00:03<00:25,   16%|█████████████▎                                                                     | 4/25 [00:04<00:2 20%|████████████████▌                                                                  | 5/25 [00:05<0 24%|███████████████████▉                                                               | 6/25 [00:0 28%|███████████████████████▏                                                           | 7/25 [ 32%|██████████████████████████▌                                                        | 8/2 36%|█████████████████████████████▉                                                     |  40%|████████████████████████████████▊                                                  44%|████████████████████████████████████                                            48%|███████████████████████████████████████▎                                    52%|██████████████████████████████████████████▋                              56%|█████████████████████████████████████████████▉                        60%|█████████████████████████████████████████████████▏                64%|████████████████████████████████████████████████████▍          68%|███████████████████████████████████████████████████████▊    72%|█████████████████████████████████████████████████████████  76%|█████████████████████████████████████████████████████████  80%|█████████████████████████████████████████████████████████  84%|█████████████████████████████████████████████████████████  88%|█████████████████████████████████████████████████████████  92%|█████████████████████████████████████████████████████████  96%|█████████████████████████████████████████████████████████ 100%|█████████████████████████████████████████████████████████ 100%|█████████████████████████████████████████████████████████ █████████████████████████| 25/25 [00:28<00:00,  1.12s/it]
 75%|█████████████████████████████████████████████████████████ 100%|█████████████████████████████████████████████████████████ █████████████████████████| 12/12 [00:00<00:00, 69.70it/s]
Traceback (most recent call last):
  File "G:\Miniconda3\envs\animatediff\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Miniconda3\envs\animatediff\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "G:\Miniconda3\envs\animatediff\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Miniconda3\envs\animatediff\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Miniconda3\envs\animatediff\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Miniconda3\envs\animatediff\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Miniconda3\envs\animatediff\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "G:\GitFork\AnimateDiff\app.py", line 180, in animate
    save_videos_grid(sample, save_sample_path)
  File "G:\GitFork\AnimateDiff\animatediff\utils\util.py", line 25, in save_videos_grid
    imageio.mimsave(path, outputs, fps=fps)
  File "G:\Miniconda3\envs\animatediff\lib\site-packages\imageio\v2.py", line 361, in mimwrite
    with imopen(uri, "wI", **imopen_args) as file:
  File "G:\Miniconda3\envs\animatediff\lib\site-packages\imageio\core\imopen.py", line 298, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `G:\GitFork\AnimateDiff\samples\Gradio-2023-08-08T20-17-31\sample\0.mp4`` with iomode `wI`.
Based on the extension, the following plugins might add capable backends:
  FFMPEG:  pip install imageio[ffmpeg]
  pyav:  pip install imageio[pyav]

**Comment by KaiJia2017** [comment]
G:\GitFork\AnimateDiff\samples\Gradio-2023-08-08T20-17-31\sample\0.mp4

**Comment by KaiJia2017** [comment]
G:\GitFork\AnimateDiff\samples\Gradio-2023-08-08T20-17-31\sample\0.mp4

no 0.mp4
