### ISSUE TITLE
加载新的 lora 遇到的问题

### ISSUE THREAD

**Issue by zhaoyz88322** [guoyww/AnimateDiff#134]
我在 gradio界面 加载新的Lora时 报错：

Traceback (most recent call last):
  File "/home/fractal/anaconda3/envs/gen2/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/fractal/anaconda3/envs/gen2/lib/python3.8/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/fractal/anaconda3/envs/gen2/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/fractal/anaconda3/envs/gen2/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/fractal/anaconda3/envs/gen2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/fractal/anaconda3/envs/gen2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/fractal/anaconda3/envs/gen2/lib/python3.8/site-packages/gradio/utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 111, in update_base_model
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(base_model_state_dict, self.vae.config)
  File "/home/fractal/www/gen2/AnimateDiff/animatediff/utils/convert_from_ckpt.py", line 570, in convert_ldm_vae_checkpoint
    new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"]
KeyError: 'encoder.conv_in.weight'

**Comment by zhaoyz88322** [comment]
![截图 2023-09-08 22-33-55](https://github.com/guoyww/AnimateDiff/assets/31495777/048e13c5-cb34-4a14-bc7b-25fd3f08d19e)

**Comment by zhaoyz88322** [comment]
我的问题 得选择 SD-1.5 和 LORA的 模型才可以
