### ISSUE TITLE
Error loading script: animatediff.py

### ISSUE THREAD

**Issue by XT-404** [guoyww/AnimateDiff#151]
Hi, error here new version . 

*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\A1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 12, in <module>
        from scripts.animatediff_latent import AnimateDiffI2VLatent
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (W:\A1111\stable-diffusion-webui\modules\sd_samplers_common.py)

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\A1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\A1111\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (W:\A1111\stable-diffusion-webui\modules\sd_samplers_common.py)

**Comment by Niutonian** [comment]
Same error here after last update:
```
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 12, in <module>
        from scripts.animatediff_latent import AnimateDiffI2VLatent
      File "E:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (E:\stable-diffusion-webui\modules\sd_samplers_common.py)

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (E:\stable-diffusion-webui\modules\sd_samplers_common.py)
```

**Comment by yebkamin** [comment]
I am also encountering the same issue and haven't found any help

**Comment by DimaSugatov** [comment]
Same error

**Comment by DBarker774** [comment]
Try updating your A1111 webUI, had the same error as @Niutonian, modules.sd_samplers_common was introduced into webUI last couple of months.
