### ISSUE TITLE
CUDA ERROR

### ISSUE THREAD

**Issue by No565** [guoyww/AnimateDiff#155]
I got this error after trying to generate something : 

RuntimeError: CUDA error: invalid configuration argument CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. 

AnimateDiff worked well previously, than i installed some other extensions which altered apparently some things.. I did not know before that i could install everything in a separate environment.. I have a list of the installed versions, but i have no list of my "before versions".

Could you specify all the dependencies so i could look after the error with the "git list" option, please ? 
Or is there a more simple way to resolve this issue ?

thank you in advance !!!

**Comment by waiting0324** [comment]
I encounter the same problem.

**Comment by jiamings** [comment]
Same here, in my case. Having a larger batch size would cause this issue.

**Comment by keenerb** [comment]
Same.  I just updated a1111 repo to latest, installed this plugin, and it's not working.

```
2023-09-21 08:45:42,386 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2023-09-21 08:45:42,917 - AnimateDiff - INFO - Hacking GroupNorm32 forward function.
2023-09-21 08:45:42,917 - AnimateDiff - INFO - Injecting motion module mm-Stabilized_mid.pth into SD1.5 UNet input blocks.
2023-09-21 08:45:42,918 - AnimateDiff - INFO - Injecting motion module mm-Stabilized_mid.pth into SD1.5 UNet output blocks.
2023-09-21 08:45:42,918 - AnimateDiff - INFO - Setting DDIM alpha.
2023-09-21 08:45:42,918 - AnimateDiff - INFO - Injection finished.
  0%|                                                                                                                                               | 0/20 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(ns5xy7m1q96xwat)', 'young girl standing in a field of flowers', '', [], 20, 'Euler a', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x0000017FFD98CF70>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, True, 'MEAN', 'AD', 1, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.animatediff_ui.AnimateDiffProcess object at 0x0000017FFD98C610>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000017FFDAA9480>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000017FFDAA94B0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000017FF666C820>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "Z:\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "Z:\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "Z:\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "Z:\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "Z:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "Z:\stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "Z:\stable-diffusion-webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "Z:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "Z:\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "Z:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "Z:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "Z:\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 169, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "Z:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "Z:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "Z:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "Z:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "Z:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "Z:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "Z:\stable-diffusion-webui\modules\sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "Z:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
        h = module(h, emb, context)
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "Z:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 26, in mm_tes_forward
        x = layer(x, context)
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "Z:\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 86, in forward
        return self.temporal_transformer(input_tensor, encoder_hidden_states, attention_mask)
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "Z:\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 150, in forward
        hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, video_length=video_length)
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "Z:\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 212, in forward
        hidden_states = attention_block(
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "Z:\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 559, in forward
        hidden_states = self._memory_efficient_attention(query, key, value, attention_mask, sd_hijack.current_optimizer.name)
      File "Z:\stable-diffusion-webui\extensions\sd-webui-animatediff\motion_module.py", line 467, in _memory_efficient_attention
        hidden_states = xformers.ops.memory_efficient_attention(
      File "z:\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 192, in memory_efficient_attention
        return _memory_efficient_attention(
      File "z:\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 290, in _memory_efficient_attention
        return _memory_efficient_attention_forward(
      File "z:\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 310, in _memory_efficient_attention_forward
        out, *_ = op.apply(inp, needs_gradient=False)
      File "z:\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\cutlass.py", line 175, in apply
        out, lse, rng_seed, rng_offset = cls.OPERATOR(
      File "z:\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 502, in __call__
        return self._op(*args, **kwargs or {})
    RuntimeError: CUDA error: invalid configuration argument
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
```

**Comment by jiamings** [comment]
I dug into this a little bit more and it may have something to do with the batch size. The temporal attention module may fire up many (B x H x W) but short (Time) attentions, which causes the configuration error in CUDA. Maybe try reducing the batch size.

**Comment by atrofeed** [comment]
I have this problem too. I have my batch count and batch size at 1. I generate at 512x512. I am using motion module v15_v2. I do not have this problem without hires.fix. When I enable hires.fix, I get this problem. Turns out, I had to remove --xformers from my webui-user.bat for it to work with hires.fix. Also, do not forget to git pull to ensure you have the latest A1111 files.

**Comment by danelo1123xp** [comment]
Same problem! Hope they will fix it

**Comment by jerzean** [comment]
same issue, but i found lowering the resolution from 512, to 380 allowed me to actually use it, but it had a super long run time like 2-3hours with default settings on a 3070 oc

**Comment by danelo1123xp** [comment]
Settings-animateDiff - change to "pytorch"

**Comment by keenerb** [comment]
> Settings-animateDiff - change to "pytorch"

What does this mean?  I have only one entry under settings-animatediff:

![image](https://github.com/guoyww/AnimateDiff/assets/1183671/d239885c-5afc-41ea-82f5-95cb4c664542)

**Comment by jerzean** [comment]
> > Settings-animateDiff - change to "pytorch"
> 
> What does this mean? I have only one entry under settings-animatediff:
> 
> ![image](https://user-images.githubusercontent.com/1183671/270082317-d239885c-5afc-41ea-82f5-95cb4c664542.png)

https://i.gyazo.com/861f13ec6d9aba8a5aa38b5eba1ab4bb.png

update your animatediff maybe?? and fully restart your A1111

**Comment by Ruikesan** [comment]
I was having this problem and found a solution although i don't recall where. Turn Token merging to 0 under the Optimizations tab in settings.

**Comment by Ssmilelife** [comment]
Where is the optimization TAB set

**Comment by Ssmilelife** [comment]
> Where is the optimization TAB set



> I was having this problem and found a solution although i don't recall where. Turn Token merging to 0 under the Optimizations tab in settings.

Where is the optimization TAB set

**Comment by kaishanguai2012** [comment]
same problem.but i fix it.in webui setting,uncheck this,i will be ok.
![QQ图片20231118203307](https://github.com/guoyww/AnimateDiff/assets/99189169/ff2d97bb-ba08-46ce-8462-211003ed9427)

**Comment by kainatquaderee** [comment]
> same problem.but i fix it.in webui setting,uncheck this,i will be ok.
> ![QQ图片20231118203307](https://github.com/guoyww/AnimateDiff/assets/99189169/ff2d97bb-ba08-46ce-8462-211003ed9427)
> 

This is the solution

**Comment by espritdautomne** [comment]
> > same problem.but i fix it.in webui setting,uncheck this,i will be ok.
> > ![QQ图片20231118203307](https://private-user-images.githubusercontent.com/99189169/283998865-ff2d97bb-ba08-46ce-8462-211003ed9427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MTg3OTQsIm5iZiI6MTczMjQxODQ5NCwicGF0aCI6Ii85OTE4OTE2OS8yODM5OTg4NjUtZmYyZDk3YmItYmEwOC00NmNlLTg0NjItMjExMDAzZWQ5NDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDAzMjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyOThlOGZkZGJmMjhmYTU1NjRiNTRiMWU2MmM5NmFiNGQ4MmY5OTBjYWJhZWZhNGU4OTI5YzM2NmMyNTQxZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OiHSJqHRENAefZJ6Apm-P8nhR4gt1l_fMCxCRAAYykg)
> 
> This is the solution

This is the way.
