### ISSUE TITLE
RuntimeError: loading state_dict for CLIPTextModel

### ISSUE THREAD

**Issue by edwinzeng2005** [guoyww/AnimateDiff#159]
I have an error. Not sure how to resolve it.

`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/animatediff/scripts/animate.py", line 159, in <module>
    main(args)
  File "/content/animatediff/scripts/animate.py", line 98, in main
    pipeline.text_encoder = convert_ldm_clip_checkpoint(base_state_dict)
  File "/content/animatediff/animatediff/utils/convert_from_ckpt.py", line 726, in convert_ldm_clip_checkpoint
    text_model.load_state_dict(text_model_dict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
	Unexpected key(s) in state_dict: "text_model.embeddings.position_ids".`

**Comment by anonymoushdafi** [comment]
hi, how did you solve it?

**Comment by edwinzeng2005** [comment]
I cannot remember how I resolved it. But I did use a diffuser in the --model-path argument.

**Comment by loboere** [comment]
Can you explain in more detail how you solved it. I have the same problem

**Comment by aulaywang** [comment]
pip install transformers==4.25.1

**Comment by Trav1slaflame** [comment]
> pip install transformers==4.25.1

This works for me! thanksssss
