### ISSUE TITLE
AttributeError: 'ModuleList' object has no attribute 'weight' 

### ISSUE THREAD

**Issue by imogenqi** [guoyww/AnimateDiff#161]
has not set the configuration `clip_sample`. `clip_sample` should be set to False in the configuration file. Please make sure to update the config accordingly as not setting `clip_sample` in the config might lead to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
  deprecate("clip_sample not set", "1.0.0", deprecation_message, standard_warn=False)
load motion module from /mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/qigege/code/AnimateDiff_models/Motion_Module/mm_sd_v15.ckpt
load lora model from /mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/qigege/code/ckpt/lora/sd_maj-lora_1/pytorch_lora_weights.safetensors
Traceback (most recent call last):
  File "/workdir/anaconda3/envs/animatediff_maj/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/workdir/anaconda3/envs/animatediff_maj/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/qigege/code/new/AnimateDiff/scripts/animate.py", line 130, in <module>
    main(args)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/qigege/code/new/AnimateDiff/scripts/animate.py", line 67, in main
    pipeline = load_weights(
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/qigege/code/new/AnimateDiff/animatediff/utils/util.py", line 148, in load_weights
    animation_pipeline = convert_lora(animation_pipeline, lora_state_dict, alpha=lora_alpha)
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/qigege/code/new/AnimateDiff/animatediff/utils/convert_lora_safetensor_to_diffusers.py", line 108, in convert_lora
    curr_layer.weight.data += alpha * torch.mm(weight_up, weight_down).to(curr_layer.weight.data.device)
  File "/workdir/anaconda3/envs/animatediff_maj/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleList' object has no attribute 'weight'

Do you have the solution? Thanks

**Comment by leebory** [comment]
May I ask if the problem has been resolved? I have also encountered the same problem

**Comment by icedoom888** [comment]
I trained my own LoRA model using the following code fro huggingface: https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py

I also have the same issue. 
Layers seem to have a different naming than the ones you use example: 'down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor.to_k_lora.down.weight'

Any help here?
