### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by K2adir** [guoyww/AnimateDiff#167]
I get the following error: ValueError: min() arg is an empty sequence

*** Error completing request
*** Arguments: ('task(ad159xaxxg3got9)', 'teddy bear ', '', [], 23, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, True, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x311b7fa90>, 0, True, 'toonyou_beta6.safetensors [e8d456c42e]', 0.8, -1, False, -1, 0, 0, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x311b7d1b0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x311b7cd60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x311b7cf70>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x310c84d60>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "/Users/k2/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/Users/k2/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/Users/k2/stable-diffusion-webui/modules/txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "/Users/k2/stable-diffusion-webui/modules/processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "/Users/k2/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_cn.py", line 87, in hacked_processing_process_images_hijack
        video_length = min(len(unit.batch_images)
    ValueError: min() arg is an empty sequence

---

![Screenshot 2023-09-27 at 8 01 59 PM](https://github.com/guoyww/AnimateDiff/assets/1120278/f6d5fbd2-1c35-4d4c-9d81-f01bdfe0accf)

**Comment by jervenclark** [comment]
Did you add video source to your animatediff input?

**Comment by K2adir** [comment]
> Did you add video source to your animatediff input?

I'm trying txt2img
