### ISSUE TITLE
Error Occur: I cannot started animate diff

### ISSUE THREAD

**Issue by yumikostl** [guoyww/AnimateDiff#180]
<img width="867" alt="image" src="https://github.com/guoyww/AnimateDiff/assets/41729879/1ca200d1-c1a4-4134-a449-4a152d637c79">
After downloading the animate diff, I encountered an issue where I am unable to open it, despite updating the diffuser. I am seeking guidance on how to resolve this problem.

**Comment by fischeroxit** [comment]
Did you try `pip install diffusers==0.11.1` ?

**Comment by yumikostl** [comment]
Yes. I have install diffusers== 0.11.1
But I still get the error after installing it.
This is the log


[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Error loading script: animatediff.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\AI\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\User\Desktop\AI\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Desktop\AI\extensions\sd-webui-animatediff-master\scripts\animatediff.py", line 9, in <module>
    from scripts.animatediff_infv2v import AnimateDiffInfV2V
  File "C:\Users\User\Desktop\AI\extensions\sd-webui-animatediff-master\scripts\animatediff_infv2v.py", line 10, in <module>
    from modules.script_callbacks import AfterCFGCallbackParams, cfg_after_cfg_callback
ImportError: cannot import name 'AfterCFGCallbackParams' from 'modules.script_callbacks' (C:\Users\User\Desktop\AI\modules\script_callbacks.py)

Error loading script: animatediff_infv2v.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\AI\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\User\Desktop\AI\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Desktop\AI\extensions\sd-webui-animatediff-master\scripts\animatediff_infv2v.py", line 10, in <module>
    from modules.script_callbacks import AfterCFGCallbackParams, cfg_after_cfg_callback
ImportError: cannot import name 'AfterCFGCallbackParams' from 'modules.script_callbacks' (C:\Users\User\Desktop\AI\modules\script_callbacks.py)

Error loading script: animatediff_latent.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\AI\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\User\Desktop\AI\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Desktop\AI\extensions\sd-webui-animatediff-master\scripts\animatediff_latent.py", line 6, in <module>
    from modules.sd_samplers_common import (approximation_indexes,
ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (C:\Users\User\Desktop\AI\modules\sd_samplers_common.py)

Error loading script: animatediff_lora.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\AI\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\User\Desktop\AI\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Desktop\AI\extensions\sd-webui-animatediff-master\scripts\animatediff_lora.py", line 6, in <module>
    from modules.paths import extensions_builtin_dir
ImportError: cannot import name 'extensions_builtin_dir' from 'modules.paths' (C:\Users\User\Desktop\AI\modules\paths.py)
