### ISSUE TITLE
Training problem (Cant use checkpoint.ckpt)

### ISSUE THREAD

**Issue by EvgeneKuklin** [guoyww/AnimateDiff#185]
I managed to train a model with my own dataset in image_finetune mode (with train.py) and acquire checkpoint.ckpt (3.3Gb, instead of usual  ~1.7Gb for MMs)
But I cant use it neither as a motion module nor as SD model
I tried to use ComfyUI-AnimateDiff-Evolved and got an error:

```
Traceback (most recent call last):
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\motion_module.py", line 130, in load_motion_module
    motion_module = AnimDiffMotionWrapper(mm_state_dict=mm_state_dict, mm_hash=model_hash, mm_name=model_name, loras=loras)
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\motion_module_ad.py", line 43, in __init__
    self.encoding_max_len = get_ad_temporal_position_encoding_max_len(mm_state_dict, mm_name)
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\motion_module_ad.py", line 26, in get_ad_temporal_position_encoding_max_len
    raise ValueError(f"No pos_encoder.pe found in mm_state_dict - {mm_type} is not a valid motion module!")
ValueError: No pos_encoder.pe found in mm_state_dict - checkpoint-epoch-1.ckpt is not a valid motion module!
```

The command I used:
`torchrun --nnodes=1 --nproc_per_node=1 train.py --config configs/training/image_finetune.yaml`

My configs:
[image_finetune.yaml.txt](https://github.com/guoyww/AnimateDiff/files/12875628/image_finetune.yaml.txt)
[training.yaml.txt](https://github.com/guoyww/AnimateDiff/files/12875629/training.yaml.txt)

Packages:
[pip_freeze.txt](https://github.com/guoyww/AnimateDiff/files/12875638/pip_freeze.txt)

What am I doing wrong?
Is other information needed from me to complete the question?
Thanks!

**Comment by EvgeneKuklin** [comment]
A motion module I got with:
`torchrun --nnodes=1 --nproc_per_node=1 train.py --config configs/training/training.yaml`

When I try to run it with:
[my_config.yaml.txt](https://github.com/guoyww/AnimateDiff/files/12894473/my.yaml.txt)

`python -m scripts.animate --config configs/prompts/my_config.yaml --pretrained_model_path F:\AI\AnimateDiff_new\models\StableDiffusion\stable-diffusion-v1-5`

I have an error:
```
(animatediff_new) PS F:\AI\AnimateDiff_new> python -m scripts.animate --config configs/prompts/my.yaml --pretrained_model_path F:\AI\AnimateDiff_new\models\StableDiffusion\stable-diffusion-v1-5
loaded temporal unet's pretrained weights from F:\AI\AnimateDiff_new\models\StableDiffusion\stable-diffusion-v1-5\unet ...
### missing keys: 560;
### unexpected keys: 0;
### Temporal Module Parameters: 417.1376 M
F:\AI\AnimateDiff_new\animatediff\pipelines\pipeline_animation.py:70: FutureWarning: The configuration file of this scheduler: DDIMScheduler {
  "_class_name": "DDIMScheduler",
  "_diffusers_version": "0.11.1",
  "beta_end": 0.012,
  "beta_schedule": "linear",
  "beta_start": 0.00085,
  "clip_sample": true,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "set_alpha_to_one": true,
  "steps_offset": 0,
  "trained_betas": null
}
 is outdated. `steps_offset` should be set to 1 instead of 0. Please make sure to update the config accordingly as leaving `steps_offset` might led to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
  deprecate("steps_offset!=1", "1.0.0", deprecation_message, standard_warn=False)
F:\AI\AnimateDiff_new\animatediff\pipelines\pipeline_animation.py:83: FutureWarning: The configuration file of this scheduler: DDIMScheduler {
  "_class_name": "DDIMScheduler",
  "_diffusers_version": "0.11.1",
  "beta_end": 0.012,
  "beta_schedule": "linear",
  "beta_start": 0.00085,
  "clip_sample": true,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "set_alpha_to_one": true,
  "steps_offset": 1,
  "trained_betas": null
}
 has not set the configuration `clip_sample`. `clip_sample` should be set to False in the configuration file. Please make sure to update the config accordingly as not setting `clip_sample` in the config might lead to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
  deprecate("clip_sample not set", "1.0.0", deprecation_message, standard_warn=False)
load motion module from F:/AI/AnimateDiff_new/outputs/training-2023-10-13T15-55-24/checkpoints/checkpoint.ckpt
### missing keys: 1246;
### unexpected keys: 560;
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\animatediff_new\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\anaconda3\envs\animatediff_new\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\AI\AnimateDiff_new\scripts\animate.py", line 123, in <module>
    main(args)
  File "F:\AI\AnimateDiff_new\scripts\animate.py", line 61, in main
    pipeline = load_weights(
  File "F:\AI\AnimateDiff_new\animatediff\utils\util.py", line 120, in load_weights
    assert len(unexpected) == 0
AssertionError
```

**Comment by EvgeneKuklin** [comment]
Alright, I've fixed the problem:

For some reason params' names of my new motion modules was named with prefix `module.`:
`module.down_blocks.0.motion_modules.0.temporal_transformer.norm.weight`
Instead of (as in valid mm's):
`down_blocks.0.motion_modules.0.temporal_transformer.norm.weight`

So the fix was just to rename them.
I replaced 110 line animatediff\utils\util.py (895f3220c06318ea0760131ec70408b466c49333)
```
unet_state_dict.update({name: param for name, param in motion_module_state_dict.items() if "motion_modules." in name})
```
to:
```
for name, param in motion_module_state_dict.items():
    if "motion_modules." in name:
        if name.startswith("module."):
            name = name.replace("module.", "")
        unet_state_dict[name] = param
```

**Comment by xiaolxl111** [comment]
Do you have a modified script? I also encountered the same problem here. thanks

**Comment by mamianshusheng** [comment]
me too. I also encountered the same problem!
