### ISSUE TITLE
Running "python app.py" got "No such file or directory - inference.yaml" error... 

### ISSUE THREAD

**Issue by Spr-Peach** [guoyww/AnimateDiff#211]
hi, help me please...   months ago it used to work fine as webui until I reinstall my system. and this time after I install it step by step as your guide this time the app.py cannot running any more...
`C:\Users\namiachy\AnimateDiff>activate animatediff

C:\Users\namiachy\AnimateDiff>conda.bat activate animatediff

(animatediff) C:\Users\namiachy\AnimateDiff>python app.py
Traceback (most recent call last):
  File "C:\Users\namiachy\AnimateDiff\app.py", line 201, in <module>
    controller = AnimateController()
  File "C:\Users\namiachy\AnimateDiff\app.py", line 69, in __init__
    self.inference_config      = OmegaConf.load("configs/inference/inference.yaml")
  File "C:\Users\namiachy\miniconda3\envs\animatediff\lib\site-packages\omegaconf\omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\namiachy\\AnimateDiff\\configs\\inference\\inference.yaml'

(animatediff) C:\Users\namiachy\AnimateDiff>
`
I'm sure of that I have the same files and directories with "https://github.com/guoyww/AnimateDiff?search=1" page and I have download all models and put them into the right path...
I ran them from the command line and everything looked fine...
help me please and thanks a lot...

**Comment by Spr-Peach** [comment]
and if I put a inference.yaml file into configs\inference\ will get another error: 
```powershell
(animatediff) C:\Users\namiachy\AnimateDiff>python app.py
C:\Users\namiachy\miniconda3\envs\animatediff\lib\site-packages\gradio\blocks.py:889: UserWarning: api_name update_stable_diffusion already exists, using update_stable_diffusion_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
C:\Users\namiachy\miniconda3\envs\animatediff\lib\site-packages\gradio\blocks.py:889: UserWarning: api_name update_motion_module already exists, using update_motion_module_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
Traceback (most recent call last):
  File "C:\Users\namiachy\AnimateDiff\app.py", line 327, in <module>
    demo = ui()
  File "C:\Users\namiachy\AnimateDiff\app.py", line 283, in ui
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

(animatediff) C:\Users\namiachy\AnimateDiff>
```

**Comment by Spr-Peach** [comment]
change to "pip install gradio==3.41.2 get all right~ close issues

**Comment by yinjiaoyuan** [comment]
Where to get configs\\inference\\inference.yaml file?

**Comment by Spr-Peach** [comment]
> Where to get configs\inference\inference.yaml file?

actually all inferences are almost the same. 4 example you can simply make a copy of inference-v1.yaml and rename it to inference.yaml...Wahahahahahaha
