### ISSUE TITLE
Problem with AnimateDiff isntallation 

### ISSUE THREAD

**Issue by Leshiy1** [guoyww/AnimateDiff#212]
Hello have a problem with installation of this plugin i was install by instruction but the AnimateDiff tab doesnt appear in WebUI but in console it gives this errors 

*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "E:\Stable\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 9, in <module>
        from scripts.animatediff_cn import AnimateDiffControl
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 18, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (E:\Stable\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_cn.py
    Traceback (most recent call last):
      File "E:\Stable\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 18, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (E:\Stable\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_i2ibatch.py
    Traceback (most recent call last):
      File "E:\Stable\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (E:\Stable\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_infotext.py
    Traceback (most recent call last):
      File "E:\Stable\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (E:\Stable\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "E:\Stable\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 11, in <module>
        from modules.sd_samplers_cfg_denoiser import CFGDenoiser, catenate_conds, subscript_cond, pad_cond
    ModuleNotFoundError: No module named 'modules.sd_samplers_cfg_denoiser'

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "E:\Stable\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 6, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (E:\Stable\stable-diffusion-webui\modules\sd_samplers_common.py)

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "E:\Stable\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 13, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (E:\Stable\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_prompt.py
    Traceback (most recent call last):
      File "E:\Stable\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_prompt.py", line 7, in <module>
        from scripts.animatediff_infotext import write_params_txt
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (E:\Stable\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "E:\Stable\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "E:\Stable\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (E:\Stable\stable-diffusion-webui\modules\processing.py)

**Comment by Leshiy1** [comment]
Figured out you if this tab doesnt appear then you just didnt update your WebUi 
solution here https://www.reddit.com/r/StableDiffusion/comments/xlj4w3/how_to_update_automatic1111_stable_diffusion_webui/
