### ISSUE TITLE
Error loading script: animatediff.py

### ISSUE THREAD

**Issue by Catalyst100** [guoyww/AnimateDiff#216]
Got two errors that are essentially the same problem (I think) but I dunno how to solve them.  
`*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 14, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 5, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'`

and

`*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 5, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'`

As far as I can tell, imageio is installed, although maybe it isn't running properly on venv... any suggestions here would be greatly appreciated.

**Comment by Catalyst100** [comment]
Nvm should probably put this in the A1111 github page
