### ISSUE TITLE
AnimatedDiff won't show up

### ISSUE THREAD

**Issue by ArchAngelAries** [guoyww/AnimateDiff#229]
I'm on latest commit of lshqqytiger's directml branch of A1111 (https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/03eec1791be011e087985ae93c1f66315d5a250e), have tried installing new instance with only AnimatedDiff installed and still doesn't show up. Can someone please help

Win 11
AMD 7900 XT

Extensions I usually have installed (don't know if any are not compatible) :

- a1111-sd-webui-tagcomplete
- adetailer
- canvas-zoom
- clip-interrogator-ext
- multidiffusion-upscaler-for-automatic1111
- openpose-editor
- sd_delete_button
- sd_lama_cleaner
- sd-civitai-browser-plus
- sd-dynamic-prompts
- sd-webui-ar
- sd-webui-aspect-ratio-helper
- sd-webui-controlnet
- sd-webui-inpaint-anything
- stable-diffusion-webui-images-browser
- stable-diffusion-webui-rembg
- stable-diffusion-webui-state
- ultimate-upscale-for-automatic1111

**Comment by ArchAngelAries** [comment]
Realized I'm getting this error, idk how to resolve:

*** Error loading script: animate.py
    Traceback (most recent call last):
      File "D:\AI-Stuff\AI\stable-diffusion-webui-directml\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI-Stuff\AI\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI-Stuff\AI\stable-diffusion-webui-directml\extensions\AnimateDiff\scripts\animate.py", line 15, in <module>
        from animatediff.models.unet import UNet3DConditionModel
      File "D:\AI-Stuff\AI\stable-diffusion-webui-directml\extensions\AnimateDiff\animatediff\models\unet.py", line 15, in <module>
        from diffusers.modeling_utils import ModelMixin
    ModuleNotFoundError: No module named 'diffusers.modeling_utils'

**Comment by krazzyremo** [comment]
same problem animatediff stop showing in a1111 today.

*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 7, in <module>
        from scripts.animatediff_cn import AnimateDiffControl
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 18, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 9, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 52
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear))):
                                                                 ^
    SyntaxError: unmatched ')'

---
*** Error loading script: animatediff_cn.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 18, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 9, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 52
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear))):
                                                                 ^
    SyntaxError: unmatched ')'

---
*** Error loading script: animatediff_infotext.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 9, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 52
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear))):
                                                                 ^
    SyntaxError: unmatched ')'

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 14, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 9, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 52
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear))):
                                                                 ^
    SyntaxError: unmatched ')'

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 10, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 9, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 52
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear))):
                                                                 ^
    SyntaxError: unmatched ')'

---
*** Error loading script: animatediff_mm.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 879, in exec_module
      File "<frozen importlib._bootstrap_external>", line 1017, in get_code
      File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 52
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear))):
                                                                 ^
    SyntaxError: unmatched ')'

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 14, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 9, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 52
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear))):
                                                                 ^
    SyntaxError: unmatched ')'

---
*** Error loading script: animatediff_prompt.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_prompt.py", line 7, in <module>
        from scripts.animatediff_infotext import write_params_txt
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 9, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 52
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear))):
                                                                 ^
    SyntaxError: unmatched ')'

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 9, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 52
        if isinstance(module, (torch.nn.Conv2d, torch.nn.Linear))):
                                                                 ^
    SyntaxError: unmatched ')'

**Comment by yuanwu2023** [comment]
我最近也在尝试修复这个问题，py的高版本diffusers插件更改了diffusers.modeling_utils的位置，我尝试把diffusers版本固定在0.14.0同时在animatediff的源码里修改from diffusers.modeling_utils import ModelMixin至from diffusers.models.modeling_utils import ModelMixin后，控制台不再报错，但是animatediff始终无法运行

**Comment by Yeetster-cmd** [comment]
Getting the same error, have been unable to fix it.

**Comment by 876128432** [comment]
问题解决了吗？最近也是总报错

**Comment by levicn** [comment]
same here

**Comment by Yeetster-cmd** [comment]
Was able to install it correctly using a guide from  [](https://stable-diffusion-art.com/animatediff/ ). Don't know what I did differently than the first time but it worked.

**Comment by gexmbla** [comment]
anyone know why the .ckpt file for the motion model will not show up in the dropdown menu? im sure i placed it in the right folder. it was showing before i updated python ...

**Comment by gonglaijiang** [comment]
have anybody solved this problem?

        from diffusers.modeling_utils import ModelMixin
    ModuleNotFoundError: No module named 'diffusers.modeling_utils'

**Comment by HaoZhang990127** [comment]
use `pip install diffusers==0.11.1 ` can solve this problem
