### ISSUE TITLE
Sdxl Error when changing the  width and height to 1920*1080

### ISSUE THREAD

**Issue by czc2000** [guoyww/AnimateDiff#231]
I'm trying to generate an animation for 1920 * 1080 resolution, but I'm getting an error.However when I used the same configuration at 1024*1024 resolution works fine. 
Saw in the error report that there seems to be some problem with the upsample in unet_block?Can you help me

Command python -m  scripts.animate --W 1920 --H 1080 --exp_config configs/prompts/1-original_sdxl.yaml

loaded temporal unet's pretrained weights from ../.cache/huggingface/hub/models--stabilityai--stable-diffusion-xl-base-1.0/snapshots/462165984030d82259a11f4367a4eed129e94a7b/unet ...
### Temporal Module Parameters: 236.7792 M
Loading motion module from models/Motion_Module/mm_sdxl_v10_beta.ckpt...
current seed: 5237799746317073769
sampling A panda standing on a surfboard in the ocean in sunset, 4k, high resolution.Realistic, Cinematic, high resolution ...
  0%|                                                                                        | 0/100 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zicong/AnimateDiff/scripts/animate.py", line 142, in <module>
    main(args)
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/zicong/AnimateDiff/scripts/animate.py", line 105, in main
    sample = pipeline(
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/zicong/AnimateDiff/animatediff/pipelines/pipeline_animation.py", line 827, in __call__
    noise_pred = self.unet(
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/zicong/AnimateDiff/animatediff/models/unet.py", line 1104, in forward
    sample = upsample_block(
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zicong/AnimateDiff/animatediff/models/unet_blocks.py", line 912, in forward
    hidden_states = upsampler(hidden_states, upsample_size)
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/diffusers/models/resnet.py", line 191, in forward
    hidden_states = F.interpolate(hidden_states, size=output_size, mode="nearest")
  File "/home/zicong/anaconda3/envs/diffusers2/lib/python3.9/site-packages/torch/nn/functional.py", line 3916, in interpolate
    raise ValueError(
ValueError: Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [34, 60] and output size of torch.Size([16, 68, 120]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.

**Comment by czc2000** [comment]
I think change animatediff/models/unet_blocks.py line 912                
```hidden_states = upsampler(hidden_states, upsample_size)```
to
```hidden_states = upsampler(hidden_states, upsample_size[1:])```
seems work well
