### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.loaders'

### ISSUE THREAD

**Issue by tankzhangying** [guoyww/AnimateDiff#253]
(animatediff) u27863@AI-02-09:/ai/u27863/AnimateDiff$ python -m scripts.animate --config configs/prompts/v2/5-RealisticVision.yaml
Traceback (most recent call last):
  File "/home/u27863/.conda/envs/animatediff/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/u27863/.conda/envs/animatediff/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/ai/u27863/AnimateDiff/scripts/animate.py", line 15, in <module>
    from animatediff.models.unet import UNet3DConditionModel
  File "/ai/u27863/AnimateDiff/animatediff/models/unet.py", line 26, in <module>
    from diffusers.loaders import UNet2DConditionLoadersMixin, AttnProcsLayers
ModuleNotFoundError: No module named 'diffusers.loaders'

diffusers had been installed 

(animatediff) u27863@AI-02-09:/ai/u27863/AnimateDiff$ pip list |grep diffuser
diffusers                 0.11.1

**Comment by JustCann** [comment]
I have this issue too, any luck?
