### ISSUE TITLE
V3- Errors when load dreambooth model realisticVisionV51_v51VAE/realisticVisionV60B1_v51VAE

### ISSUE THREAD

**Issue by lusenkong** [guoyww/AnimateDiff#255]
I downloaded the realisticVisionV51_v51 and realisticVisionV60B1_v51 according to the intrudution link, but errors occurred when loading them...

### Motion Module Parameters: 417.1376 M
loading controlnet checkpoint from models/SparseCtrl/v3_sd15_sparsectrl_rgb.ckpt ...
controlnet image paths:
__assets__/demos/image/RealisticVision_firework.png
load motion module from models/Motion_Module/v3_sd15_mm.ckpt
load dreambooth model from models/DreamBooth_LoRA/realisticVisionV51_v51VAE.safetensors
Traceback (most recent call last):
  File "/home/tione/notebook/lskong2/softwares/anaconda3/envs/dsd/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tione/notebook/lskong2/softwares/anaconda3/envs/dsd/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tione/notebook/lskong2/projects/5.image_2_video/AnimateDiff/scripts/animate.py", line 196, in <module>
    main(args)
  File "/home/tione/notebook/lskong2/softwares/anaconda3/envs/dsd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tione/notebook/lskong2/projects/5.image_2_video/AnimateDiff/scripts/animate.py", line 126, in main
    pipeline = load_weights(
  File "/home/tione/notebook/lskong2/projects/5.image_2_video/AnimateDiff/animatediff/utils/util.py", line 133, in load_weights
    animation_pipeline.vae.load_state_dict(converted_vae_checkpoint)
  File "/home/tione/notebook/lskong2/softwares/anaconda3/envs/dsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
	Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias". 
	Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.value.weight".

**Comment by lusenkong** [comment]
downgrade diffuser from 0.23 to 0.11 , problem solved ...
