### ISSUE TITLE
v3_sd15_adapter.ckpt in LoRA loader

### ISSUE THREAD

**Issue by nyukers** [guoyww/AnimateDiff#257]
[AnimateDiffEvo] - INFO - Loading motion module v3_sd15_mm.ckpt
[AnimateDiffEvo] - INFO - Loading motion LoRA v3_sd15_adapter.ckpt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "d:\SDComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "d:\SDComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "d:\SDComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\nodes.py", line 115, in load_mm_and_inject_params
    motion_model = load_motion_module(model_name, model, motion_lora=motion_lora, motion_model_settings=motion_model_settings)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_injection.py", line 206, in load_motion_module
    load_motion_lora_as_patches(motion_model, lora)
  File "D:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_injection.py", line 148, in load_motion_lora_as_patches
    raise ValueError(f"'{lora.name}' contains no temporal keys; it is not a valid motion LoRA!")
ValueError: **'v3_sd15_adapter.ckpt' contains no temporal keys; it is not a valid motion LoRA**!

What am I doing wrong?

**Comment by youcanyoubing** [comment]
这个模型应该放在那里？

**Comment by wangsan0315** [comment]
> v3_sd15_adapter.ckpt 是lora模型，需要放在lora文件夹内，不能放在motion lora 文件夹内，也不能在 motion lora 节点加载

请问这个lora模型有SDXL的吗
