### ISSUE TITLE
Can´t export MP4 - UnknownCodecError: libx264

### ISSUE THREAD

**Issue by amauri-di-maia** [guoyww/AnimateDiff#261]
Hello guys Im looking for some help, I can export in GIF but when I try to export in MP4 I get this error:

2024-01-05 00:11:04,555 - AnimateDiff - INFO - AnimateDiff process start.
2024-01-05 00:11:04,556 - AnimateDiff - INFO - Loading motion module mm_sd_v14.ckpt from K:\AI Stuff\stable-diffusion-webui\extensions\sd-webui-animatediff\model\mm_sd_v14.ckpt
2024-01-05 00:11:05,162 - AnimateDiff - INFO - Guessed mm_sd_v14.ckpt architecture: MotionModuleType.AnimateDiffV1
2024-01-05 00:11:07,487 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2024-01-05 00:11:08,400 - AnimateDiff - INFO - Hacking SD1.5 GroupNorm32 forward function.
2024-01-05 00:11:08,400 - AnimateDiff - INFO - Injecting motion module mm_sd_v14.ckpt into SD1.5 UNet input blocks.
2024-01-05 00:11:08,400 - AnimateDiff - INFO - Injecting motion module mm_sd_v14.ckpt into SD1.5 UNet output blocks.
2024-01-05 00:11:08,401 - AnimateDiff - INFO - Setting DDIM alpha.
2024-01-05 00:11:08,433 - AnimateDiff - INFO - Injection finished.
2024-01-05 00:11:08,433 - AnimateDiff - INFO - Hacking CFGDenoiser forward function.
2024-01-05 00:11:08,433 - AnimateDiff - INFO - Hacking ControlNet.
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:42<00:00,  1.42s/it]
2024-01-05 00:11:55,444 - AnimateDiff - INFO - Restoring ControlNet.███████████████████| 30/30 [00:40<00:00,  1.40s/it]
2024-01-05 00:11:55,444 - AnimateDiff - INFO - Restoring CFGDenoiser forward function.
2024-01-05 00:11:55,445 - AnimateDiff - INFO - Restoring DDIM alpha.
2024-01-05 00:11:55,445 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
2024-01-05 00:11:55,446 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2024-01-05 00:11:55,447 - AnimateDiff - INFO - Restoring SD1.5 GroupNorm32 forward function.
2024-01-05 00:11:55,448 - AnimateDiff - INFO - Removal finished.
2024-01-05 00:11:55,449 - AnimateDiff - INFO - Merging images into GIF.
2024-01-05 00:11:55,466 - AnimateDiff - INFO - Saving outputs\txt2img-images\AnimateDiff\2024-01-05\00000-1958578848.mp4*** Error running postprocess: K:\AI Stuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py    Traceback (most recent call last):
      File "K:\AI Stuff\stable-diffusion-webui\modules\scripts.py", line 750, in postprocess
        script.postprocess(p, processed, *script_args)
      File "K:\AI Stuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 96, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "K:\AI Stuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 39, in output
        video_paths += self._save(params, frame_list, video_path_prefix, res, i)
      File "K:\AI Stuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 236, in _save
        stream = output.add_stream('libx264', params.fps, options=options)
      File "av\\container\\output.pyx", line 62, in av.container.output.OutputContainer.add_stream
      File "av\\codec\\codec.pyx", line 179, in av.codec.codec.Codec.__cinit__
      File "av\\codec\\codec.pyx", line 187, in av.codec.codec.Codec._init
    av.codec.codec.UnknownCodecError: libx264

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:44<00:00,  1.50s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:44<00:00,  1.40s/it]

I followed the tutorial of https://www.nextdiffusion.ai/tutorials/how-to-install-ffmpeg-on-windows-for-stable-diffusion-a-comprehensive-guide, Im really stuck in this situation, I tried to search on Google but at least for me I had no luck, any help is more than welcome.

**Comment by huanhuachenfeng** [comment]
Same problem, but the code is a little different:

`Error occurred when executing ADE_AnimateDiffCombine:

expected str, bytes or os.PathLike object, not NoneType

File "E:\Comfyui\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfyui\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfyui\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfyui\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\nodes_deprecated.py", line 253, in generate_gif
with open(video_format_path, 'r') as stream:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by huanhuachenfeng** [comment]
Same problem, but the code is a little different:

```python
Error occurred when executing ADE_AnimateDiffCombine:

expected str, bytes or os.PathLike object, not NoneType

File "E:\Comfyui\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfyui\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfyui\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfyui\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\nodes_deprecated.py", line 253, in generate_gif
with open(video_format_path, 'r') as stream:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
