### ISSUE TITLE
Error when installing AnimateDiff

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [guoyww/AnimateDiff#273]
I'm using version 1.5.2 because 1.6 never works for me and gives me a bunch of socket errors.
```
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 7, in <module>
        from scripts.animatediff_cn import AnimateDiffControl
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 19, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\masterbranch\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_cn.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 19, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\masterbranch\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_i2ibatch.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\masterbranch\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_infotext.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\masterbranch\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_infv2v.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 11, in <module>
        from modules.sd_samplers_cfg_denoiser import CFGDenoiser, catenate_conds, subscript_cond, pad_cond
    ModuleNotFoundError: No module named 'modules.sd_samplers_cfg_denoiser'

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 6, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (D:\ai\masterbranch\stable-diffusion-webui\modules\sd_samplers_common.py)

---
*** Error loading script: animatediff_lcm.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_lcm.py", line 9, in <module>
        from modules import shared, sd_samplers_cfg_denoiser, sd_samplers_kdiffusion
    ImportError: cannot import name 'sd_samplers_cfg_denoiser' from 'modules' (unknown location)

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 14, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\masterbranch\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_prompt.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_prompt.py", line 7, in <module>
        from scripts.animatediff_infotext import write_params_txt
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infotext.py", line 6, in <module>
        from scripts.animatediff_ui import AnimateDiffProcess
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\masterbranch\stable-diffusion-webui\modules\processing.py)

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 11, in <module>
        from modules.processing import (StableDiffusionProcessingImg2Img,
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (D:\ai\masterbranch\stable-diffusion-webui\modules\processing.py)

```

**Comment by ENTPRESTIGIOUS** [comment]
Updated to new version and works
