### ISSUE TITLE
Getting `animatediff_i2ibatch` error message from the latest version of animateDiff v2.0.0-a

### ISSUE THREAD

**Issue by speedwar** [guoyww/AnimateDiff#300]
Getting `animatediff_i2ibatch` error message from the latest version of animateDiff v2.0.0-a

thanks

`*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "C:\Users\speedwar\git\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\speedwar\git\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\speedwar\git\stable-diffusion-webui\extensions\webui-animatediff\scripts\animatediff.py", line 7, in <module>
        from scripts.animatediff_cn import AnimateDiffControl
      File "C:\Users\speedwar\git\stable-diffusion-webui\extensions\webui-animatediff\scripts\animatediff_cn.py", line 21, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
    ImportError: cannot import name 'animatediff_i2ibatch' from 'scripts.animatediff_i2ibatch' (C:\Users\speedwar\git\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py)

---
*** Error loading script: animatediff_cn.py
    Traceback (most recent call last):
      File "C:\Users\speedwar\git\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\speedwar\git\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\speedwar\git\stable-diffusion-webui\extensions\webui-animatediff\scripts\animatediff_cn.py", line 21, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
    ImportError: cannot import name 'animatediff_i2ibatch' from 'scripts.animatediff_i2ibatch' (C:\Users\speedwar\git\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py)

---
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "C:\Users\speedwar\git\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\speedwar\git\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\speedwar\git\stable-diffusion-webui\extensions\webui-animatediff\scripts\animatediff_ui.py", line 10, in <module>
        from scripts.animatediff_i2ibatch import animatediff_i2ibatch
    ImportError: cannot import name 'animatediff_i2ibatch' from 'scripts.animatediff_i2ibatch' (C:\Users\speedwar\git\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py)`

**Comment by EvanMei1985** [comment]
me too
