### ISSUE TITLE
AnimateDiff is running abnormally, can you please take a look? AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

### ISSUE THREAD

**Issue by fatyi** [guoyww/AnimateDiff#301]
** Error executing callback cfg_denoiser_callback for D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\script_callbacks.py", line 230, in cfg_denoiser_callback
        c.callback(params)
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 163, in animatediff_on_cfg_denoiser
        cfg_params.text_cond = ad_params.text_cond
    AttributeError: 'AnimateDiffProcess' object has no attribute 'text_cond'

---version: [v1.8.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/bef51aed032c0aaa5cfd80445bc4cf0d85b408b5)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2

**Comment by muze75** [comment]
This is currently happening with me on SD webui 1.8.0 but only when I use animatediff in conjunction with controlnet.

**Comment by GoZippy** [comment]
same issue

**Comment by jywyq** [comment]
same here

**Comment by simbiant** [comment]
same, anyone know how to fix?

**Comment by fanchunmeng-98** [comment]
same here

**Comment by simbiant** [comment]
Delete your version of animateDiff and install fork https://github.com/light-and-ray/sd-webui-animatediff- 
No errors for me
