### ISSUE TITLE
AttributeError: 'Row' object has no attribute 'style'

### ISSUE THREAD

**Issue by 12441409** [guoyww/AnimateDiff#305]
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "/app/AnimateDiff/app.py", line 327, in <module>
    demo = ui()
  File "/app/AnimateDiff/app.py", line 283, in ui
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by marioloko** [comment]
I think that the problem is that you are using gradio version 4 or above.

With gradio==3.41.2 it works fine for me.

```
pip uninstall gradio
pip install gradio==3.41.2
```

Fixed that for me
