### ISSUE TITLE
TypeError: EulerDiscreteScheduler.__init__() got an unexpected keyword argument 'steps_offset'

### ISSUE THREAD

**Issue by wangxin1999** [guoyww/AnimateDiff#309]
Traceback (most recent call last):
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/gradio/routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/root/autodl-tmp/AnimateDiff/app.py", line 158, in animate
    scheduler=scheduler_dict[sampler_dropdown](**OmegaConf.to_container(self.inference_config.noise_scheduler_kwargs))
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 567, in inner_init
    init(self, *args, **init_kwargs)
TypeError: EulerDiscreteScheduler.__init__() got an unexpected keyword argument 'steps_offset'

How to fix it ?

**Comment by RaGnar0K12138** [comment]
I have the same problem
