### ISSUE TITLE
AnimateDiff插件里面 Motion module 是空的

### ISSUE THREAD

**Issue by yszza1997** [guoyww/AnimateDiff#349]
安装了AnimateDiff插件，把下好的model放在了\extensions\sd-webui-animatediff\model 里面，在第一次使用时能加载model，后续重启webui后就加载不出来model了，

**Comment by yszza1997** [comment]
重新换了一个model，现在txt 2 img 出现报错：- AnimateDiff - WARNING - No motion module detected, falling back to the original forward. You are most likely using !Adetailer. !Adetailer post-process your outputs sequentially, and there will NOT be motion module in your UNet, so there might be NO temporal consistency within the inpainted face. Use at your own risk. If you really want to pursue inpainting with AnimateDiff inserted into UNet, use Segment Anything to generate masks for each frame and inpaint them with AnimateDiff + ControlNet. Note that my proposal might be good or bad, do your own research to figure out the best way.
100%|████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.11it/s]
*** Error running postprocess_batch_list: C:\Users\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 873, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "C:\Users\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 84, in postprocess_batch_list
        params.prompt_scheduler.save_infotext_img(p)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'

---
*** Error running postprocess: C:\Users\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\Users\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 857, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\Users\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 94, in postprocess
        params.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'
