### ISSUE TITLE
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\Newton\Documents\aistuff\AnimateDiff\venv\Lib\site-packages\torch\lib\torch_python.dll"

### ISSUE THREAD

**Issue by NNewtonn** [guoyww/AnimateDiff#374]
Installed all requirements on a venv, torch files are there but for some reason python is unable to find it
Python version 3.11.0b3

Traceback (most recent call last):
  File "C:\Users\Newton\Documents\aistuff\AnimateDiff\app.py", line 4, in <module>
    import torch
    ^^^^^^^^^^^^
  File "C:\Users\Newton\Documents\aistuff\AnimateDiff\venv\Lib\site-packages\torch\__init__.py", line 132, in <module>
    raise err
    ^^^^^^^^^
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\Newton\Documents\aistuff\AnimateDiff\venv\Lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
(venv) PS C:\Users\Newton\Documents\aistuff\AnimateDiff>

**Comment by NNewtonn** [comment]
Its only visual studio that has the issue, any idea? I only have 1 version of python so that shouldnt be an issue, it works if executed from powershell

**Comment by NNewtonn** [comment]
it now works from powershell but not from visualstudio code and this was after using `pip install numpy==1.24.1`
