### ISSUE TITLE
dependency issues suddenly arise

### ISSUE THREAD

**Issue by TheOneTrueGuy** [guoyww/AnimateDiff#378]
Suddenly started getting this error chain:
available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-24 17:05:29.697675: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/AnimateDiff-init/scripts/animate.py", line 9, in <module>
    import diffusers
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 46, in <module>
    from .pipeline_utils import DiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipeline_utils.py", line 38, in <module>
    from .schedulers.scheduling_utils import SCHEDULER_CONFIG_NAME
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/__init__.py", line 51, in <module>
    from .scheduling_ddpm_flax import FlaxDDPMScheduler
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_ddpm_flax.py", line 80, in <module>
    class FlaxDDPMScheduler(FlaxSchedulerMixin, ConfigMixin):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_ddpm_flax.py", line 216, in FlaxDDPMScheduler
    key: random.KeyArray,
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py", line 54, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'

Have found a work around by installing an earlier jax but still getting other errors even after fixing the unexpected key error:

/content/AnimateDiff-init

To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-24 17:10:12.105599: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
loaded temporal unet's pretrained weights from /content/AnimateDiff-init/models/StableDiffusion/stable-diffusion-v1-5/unet ...
### Temporal Module Parameters: 417.1376 M
Warning: 320 unexpected keys in motion module were not loaded:
['down_blocks.0.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.processor.to_q_lora.down.weight', 
{removed long block here}
'up_blocks.3.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.processor.to_v_lora.down.weight', 'up_blocks.3.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.processor.to_v_lora.up.weight', 'up_blocks.3.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.processor.to_out_lora.down.weight', 'up_blocks.3.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.processor.to_out_lora.up.weight']
config.json: 100% 4.52k/4.52k [00:00<00:00, 21.1MB/s]
model.safetensors: 100% 1.71G/1.71G [00:05<00:00, 299MB/s]
Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel: ['vision_model.encoder.layers.22.self_attn.k_proj.weight', 'vision_model.encoder.layers.22.mlp.fc1.bias', 
{removed long block here}
'vision_model.encoder.layers.9.self_attn.out_proj.weight', 'vision_model.encoder.layers.20.self_attn.q_proj.bias', 'vision_model.encoder.layers.19.layer_norm1.bias', 'vision_model.encoder.layers.8.self_attn.k_proj.bias']
- This IS expected if you are initializing CLIPTextModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CLIPTextModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/AnimateDiff-init/scripts/animate.py", line 229, in <module>
    main(args)
  File "/content/AnimateDiff-init/scripts/animate.py", line 153, in main
    (lora_path, lora_alpha) = lora_weights.split(':')
ValueError: not enough values to unpack (expected 2, got 1)

running on a Google Colab instance, my fork is here: https://github.com/TheOneTrueGuy/AnimateDiff-init

**Comment by TheOneTrueGuy** [comment]
sorry, meant to post this to a different branch not the core one. Struggling with using an init image over here, will close issue now.
