### ISSUE TITLE
Colab doesn't work

### ISSUE THREAD

**Issue by qo4on** [guoyww/AnimateDiff#404]
The [link](https://huggingface.co/runwayml/stable-diffusion-v1-5) in your [colab](https://colab.research.google.com/github/camenduru/AnimateDiff-colab/blob/main/AnimateDiff_colab.ipynb) doesn't work

```
/content/animatediff
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/animatediff/scripts/animate.py", line 9, in <module>
    import diffusers
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 46, in <module>
    from .pipeline_utils import DiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipeline_utils.py", line 35, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/usr/local/lib/python3.10/dist-packages/diffusers/dynamic_modules_utils.py", line 29, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)
```

**Comment by MagicianAT** [comment]
pip install huggingface_hub==0.25.2 
Try going back to version 0.25.2

**Comment by qo4on** [comment]
```
!pip install huggingface_hub==0.25.2

/content/animatediff
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/animatediff/scripts/animate.py", line 9, in <module>
    import diffusers
  File "/usr/local/lib/python3.11/dist-packages/diffusers/__init__.py", line 46, in <module>
    from .pipeline_utils import DiffusionPipeline
  File "/usr/local/lib/python3.11/dist-packages/diffusers/pipeline_utils.py", line 38, in <module>
    from .schedulers.scheduling_utils import SCHEDULER_CONFIG_NAME
  File "/usr/local/lib/python3.11/dist-packages/diffusers/schedulers/__init__.py", line 51, in <module>
    from .scheduling_ddpm_flax import FlaxDDPMScheduler
  File "/usr/local/lib/python3.11/dist-packages/diffusers/schedulers/scheduling_ddpm_flax.py", line 80, in <module>
    class FlaxDDPMScheduler(FlaxSchedulerMixin, ConfigMixin):
  File "/usr/local/lib/python3.11/dist-packages/diffusers/schedulers/scheduling_ddpm_flax.py", line 216, in FlaxDDPMScheduler
    key: random.KeyArray,
         ^^^^^^^^^^^^^^^
AttributeError: module 'jax.random' has no attribute 'KeyArray'
```

**Comment by DjamilDowlut** [comment]
same error as you, both of them

can someone help

**Comment by ljc02** [comment]
any one solve this?

**Comment by UrszulaCzerwinska** [comment]
same here
