### ISSUE TITLE
i am getting "AssertionError"

### ISSUE THREAD

**Issue by dbodbo** [guoyww/AnimateDiff#41]
(animatediff) PS F:\animediff\AnimateDiff> python -m scripts.animate --config configs/prompts/1-ToonYou.yaml
C:\Users\*****\miniconda3\envs\animatediff\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\*****\miniconda3\envs\animatediff\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")
loaded temporal unet's pretrained weights from models/StableDiffusion\unet ...
### Temporal Module Parameters: 417.1376 M
Traceback (most recent call last):
  File "C:\Users\*****\miniconda3\envs\animatediff\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\*****\miniconda3\envs\animatediff\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\animediff\AnimateDiff\scripts\animate.py", line 159, in <module>
    main(args)
  File "F:\animediff\AnimateDiff\scripts\animate.py", line 56, in main
    else: assert False
AssertionError

**Comment by Wawoul** [comment]
I got this too, noticed that xformers wasn't installed in my activate animatediff environment (check by running ' python -m xformers.info ' after ' conda activate animatediff ') then if not there, install it again with ' pip install xformers==0.0.20 '

**Comment by song-wensong** [comment]
loaded 3D unet's pretrained weights from models/StableDiffusion/stable-diffusion-v1-5/unet ...
### missing keys: 560; 
### unexpected keys: 0;
What could be the reason for the presence of missing keys?

**Comment by Henrik-hw** [comment]
> (animatediff) PS F:\animediff\AnimateDiff> python -m scripts.animate --config configs/prompts/1-ToonYou.yaml C:\Users\dbodbo\miniconda3\envs\animatediff\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\dbodbo\miniconda3\envs\animatediff\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax. warn(f"Failed to load image Python extension: {e}") loaded temporal unet's pretrained weights from models/StableDiffusion\unet ...
> 
> ### missing keys: 560;
> ### unexpected keys: 0;
> ### Temporal Module Parameters: 417.1376 M
> Traceback (most recent call last): File "C:\Users\dbodbo\miniconda3\envs\animatediff\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\dbodbo\miniconda3\envs\animatediff\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "F:\animediff\AnimateDiff\scripts\animate.py", line 159, in main(args) File "F:\animediff\AnimateDiff\scripts\animate.py", line 56, in main else: assert False AssertionError

Have you resolved this error?
