### ISSUE TITLE
A matching Triton is not available, some optimizations will not be enabled. Error caught was: No module named 'triton'

### ISSUE THREAD

**Issue by morffi** [guoyww/AnimateDiff#43]
~/AnimateDiff$ python -m scripts.animate --config configs/prompts/2-Lyriel.yaml 
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/animatediff/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/animatediff/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/AnimateDiff/scripts/animate.py", line 159, in <module>
    main(args)
  File "/home/ubuntu/AnimateDiff/scripts/animate.py", line 51, in main
    text_encoder = CLIPTextModel.from_pretrained(args.pretrained_model_path, subfolder="text_encoder")
  File "/home/ubuntu/anaconda3/envs/animatediff/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2230, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/ubuntu/anaconda3/envs/animatediff/lib/python3.10/site-packages/transformers/modeling_utils.py", line 386, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
OSError: No such device (os error 19)

**Comment by Bendito999** [comment]
on mine I had fixed this with
pip3 install triton

**Comment by morffi** [comment]
> on mine I had fixed this with pip3 install triton

Didn't help me

**Comment by Bendito999** [comment]
I also had to do this 
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

**Comment by dancemanUK** [comment]
windows 10 need  triton-2.0.0-cp310-cp310-win_amd64.whl1
