### ISSUE TITLE
how to use lora generate gif

### ISSUE THREAD

**Issue by magicwang1111** [guoyww/AnimateDiff#60]
lyriel_v16:
  base: "models/DreamBooth_LoRA/lyriel_v16.safetensors"
  path: "models/DreamBooth_LoRA/DANWGFWL.safetensors"
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  seed:           [10788741199826055526, 6520604954829636163, 6519455744612555650]
  steps:          35
  guidance_scale: 7

  prompt:
    - "1 girl solo, perfect_hand, (8k, RAW photo, best quality, masterpiece:1.2), (realistic, photo-realistic:1.4), (extremely detailed CG unity 8k wallpaper),(full body), (neon lights), machop, mechanical arms, hanfu, <lora:DANWGFWL:0.6>,Chinese clothes, dress, pretty face,(dark shot:1.1), epic realistic, RAW, analog, sharp focus, volumetric fog"
    - "(masterpiece, best quality), 1girl, nude, closed eyes, upper body, splashing, abstract, psychedelic,"
    - "(masterpiece, best quality), 1boy, muscular, beard, cyberpunk, (blurry, bokeh, fisheye lens), night, looking at viewer, contrast, contrapposto, neon oversized jacket,"

  n_prompt:
    - "(worst quality, low quality:2), monochrome, zombie,overexposure, watermark,text,bad anatomy,bad hand,extra hands,extra fingers,too many fingers,fused fingers,bad arm,distorted arm,extra arms,fused arms,extra legs,missing leg,disembodied leg,extra nipples, detached arm, liquid hand,inverted hand,disembodied limb, small breasts, loli, oversized head,extra body,completely nude, extra navel,easynegative,(hair between eyes),sketch, duplicate, ugly, huge eyes, text, logo, worst face, (bad and mutated hands:1.3), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), ((2girl)), (deformed fingers:1.2), (long fingers:1.2),(bad-artist-anime), bad-artist, bad hand, extra legs ,(ng_deepnegative_v1_75t)"
    - "(worst quality, low quality:2), monochrome, zombie,overexposure, watermark,text,bad anatomy,bad hand,extra hands,extra fingers,too many fingers,fused fingers,bad arm,distorted arm,extra arms,fused arms,extra legs,missing leg,disembodied leg,extra nipples, detached arm, liquid hand,inverted hand,disembodied limb, small breasts, loli, oversized head,extra body,completely nude, extra navel,easynegative,(hair between eyes),sketch, duplicate, ugly, huge eyes, text, logo, worst face, (bad and mutated hands:1.3), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), ((2girl)), (deformed fingers:1.2), (long fingers:1.2),(bad-artist-anime), bad-artist, bad hand, extra legs ,(ng_deepnegative_v1_75t)"
    - "(worst quality, low quality:2), monochrome, zombie,overexposure, watermark,text,bad anatomy,bad hand,extra hands,extra fingers,too many fingers,fused fingers,bad arm,distorted arm,extra arms,fused arms,extra legs,missing leg,disembodied leg,extra nipples, detached arm, liquid hand,inverted hand,disembodied limb, small breasts, loli, oversized head,extra body,completely nude, extra navel,easynegative,(hair between eyes),sketch, duplicate, ugly, huge eyes, text, logo, worst face, (bad and mutated hands:1.3), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), ((2girl)), (deformed fingers:1.2), (long fingers:1.2),(bad-artist-anime), bad-artist, bad hand, extra legs ,(ng_deepnegative_v1_75t)"

**Comment by magicwang1111** [comment]
Traceback (most recent call last):
File "C:\Users\admin\anaconda3\envs\animatediff\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\admin\anaconda3\envs\animatediff\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "D:\AnimateDiff\scripts\animate.py", line 159, in <module>
main(args)
File "D:\AnimateDiff\scripts\animate.py", line 103, in main
pipeline = convert_lora(pipeline, state_dict, alpha=model_config.lora_alpha)
File "C:\Users\admin\anaconda3\envs\animatediff\lib\site-packages\omegaconf\dictconfig.py", line 355, in getattr
self._format_and_raise(
File "C:\Users\admin\anaconda3\envs\animatediff\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
format_and_raise(
File "C:\Users\admin\anaconda3\envs\animatediff\lib\site-packages\omegaconf_utils.py", line 899, in format_and_raise
_raise(ex, cause)
File "C:\Users\admin\anaconda3\envs\animatediff\lib\site-packages\omegaconf_utils.py", line 797, in _raise
raise ex.with_traceback(sys.exc_info()[2]) # set env var OC_CAUSE=1 for full trace
File "C:\Users\admin\anaconda3\envs\animatediff\lib\site-packages\omegaconf\dictconfig.py", line 351, in getattr
return self._get_impl(
File "C:\Users\admin\anaconda3\envs\animatediff\lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
node = self._get_child(
File "C:\Users\admin\anaconda3\envs\animatediff\lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child
child = self._get_node(
File "C:\Users\admin\anaconda3\envs\animatediff\lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key lora_alpha
full_key: lyriel_v16.lora_alpha
object_type=dict

**Comment by guoyww** [comment]
Hi, it seems you should add the key "lora_alpha" in your config file, e.g.,

...
path: "models/DreamBooth_LoRA/DANWGFWL.safetensors"
lora_alpha: 0.8
...
