### ISSUE TITLE
ResolvePackageNotFound: xformers

### ISSUE THREAD

**Issue by DuckersMcQuack** [guoyww/AnimateDiff#64]
(base) H:\Stablediff\aniumateddiff\AnimateDiff\AnimateDiff>conda env create -f environment.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - xformers
  
  I tried using anaconda navigator as well for a premade venv, then i got: 
  
  ModuleNotFoundError: No module named 'diffusers.modeling_utils'
  
  Nor can i download the other configs as you used google drive, download quota was reached, so can't download those.

**Comment by Skquark** [comment]
I'm also getting the same error in my GUI implementation:
File "/content/animatediff/scripts/animate.py", line 15, in <module>
from animatediff.models.unet import UNet3DConditionModel
File "/content/animatediff/animatediff/models/unet.py", line 15, in <module>
from diffusers.modeling_utils import ModelMixin
ModuleNotFoundError: No module named 'diffusers.modeling_utils'

I've got my diffuser[torch] installed, and all the other requirements look just fine.  I could show all my code, but not sure if this ModuleNotFoundError has anything to do with the code leading up to running the command.  Any clues why it can't find modeling_utils?

**Comment by k-a-s-o-u** [comment]
I've got the same error.
When run this

python -m scripts.animate --config configs/prompts/1-ToonYou.yaml

ModuleNotFoundError: No module named 'diffusers.modeling_utils'

**Comment by thxtech** [comment]
I also got the same error.

```
❯ python -m scripts.animate --config ./config.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/hoge/AnimateDiff/scripts/animate.py", line 15, in <module>
    from animatediff.models.unet import UNet3DConditionModel
  File "/home/hoge/AnimateDiff/animatediff/models/unet.py", line 15, in <module>
    from diffusers.modeling_utils import ModelMixin
ModuleNotFoundError: No module named 'diffusers.modeling_utils'
```

```
❯ python -V
Python 3.10.6
❯ python -m pip list
Package                  Version
------------------------ ----------
antlr4-python3-runtime   4.9.3
beautifulsoup4           4.12.2
certifi                  2023.7.22
charset-normalizer       3.2.0
cmake                    3.27.0
diffusers                0.19.0
filelock                 3.12.2
fsspec                   2023.6.0
gdown                    4.7.1
huggingface-hub          0.16.4
idna                     3.4
importlib-metadata       6.8.0
Jinja2                   3.1.2
lit                      16.0.6
MarkupSafe               2.1.3
mpmath                   1.3.0
networkx                 3.1
numpy                    1.25.1
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
omegaconf                2.3.0
packaging                23.1
Pillow                   10.0.0
pip                      22.0.2
PySocks                  1.7.1
PyYAML                   6.0.1
regex                    2023.6.3
requests                 2.31.0
safetensors              0.3.1
setuptools               59.6.0
six                      1.16.0
soupsieve                2.4.1
sympy                    1.12
tokenizers               0.13.3
torch                    2.0.1
tqdm                     4.65.0
transformers             4.31.0
triton                   2.0.0
typing_extensions        4.7.1
urllib3                  2.0.4
wheel                    0.41.0
zipp                     3.16.2
```

```
❯ git show
commit 53c63ad8391d7095ab5364c13b4aa3a7d183dac5 (HEAD -> main, origin/main, origin/HEAD)
Author: Yuwei Guo <guoyuwei@pjlab.org.cn>
Date:   Fri Jul 21 10:36:35 2023 +0800

    update
```

**Comment by Skquark** [comment]
I was integrating it into my all-in-one Diffusers toolkit GUI that requires the latest version of diffusers, not 0.11.1, as well as Torch >= 2.0... If the solution is downgrading, I can't use it..
Instead I found a totally refactored Fork by Neggles that he adapted to use the newer diffusers version and updated the other required packages, plus some extra features added. Also uses a json file instead of yaml for the config file, which I liked better.  If anyone else is interested, it's at https://github.com/neggles/animatediff-cli and being actively refined.  The official repo should be updated to match this in my opinion..
