### ISSUE TITLE
generating video error? Crash 

### ISSUE THREAD

**Issue by Maki9009** [guoyww/AnimateDiff#80]
after it does 25 samples, 
it crashes with this Error
Traceback (most recent call last):
  File "C:\Users\mahmo\miniconda3\envs\animatediff\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mahmo\miniconda3\envs\animatediff\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\AnimateDiff\scripts\animate.py", line 159, in <module>
    main(args)
  File "E:\AnimateDiff\scripts\animate.py", line 125, in main
    sample = pipeline(
  File "C:\Users\mahmo\miniconda3\envs\animatediff\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\AnimateDiff\animatediff\pipelines\pipeline_animation.py", line 419, in __call__
    video = self.decode_latents(latents)
  File "E:\AnimateDiff\animatediff\pipelines\pipeline_animation.py", line 246, in decode_latents
    video.append(self.vae.decode(latents[frame_idx:frame_idx+1]).sample)
  File "C:\Users\mahmo\miniconda3\envs\animatediff\lib\site-packages\diffusers\models\vae.py", line 605, in decode
    decoded = self._decode(z).sample
  File "C:\Users\mahmo\miniconda3\envs\animatediff\lib\site-packages\diffusers\models\vae.py", line 576, in _decode
    z = self.post_quant_conv(z)
  File "C:\Users\mahmo\miniconda3\envs\animatediff\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mahmo\miniconda3\envs\animatediff\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\mahmo\miniconda3\envs\animatediff\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same

**Comment by hila-chefer** [comment]
same here :( any ideas on how to solve this?
