### ISSUE TITLE
HFValidationError when running default scripts

### ISSUE THREAD

**Issue by NaturalFigurehead** [guoyww/AnimateDiff#84]
Ubuntu 20.4

Follow all the installation instructions. Install ToonYou model.

run `python -m scripts.animate --config configs/prompts/1-ToonYou.yaml`

Output:
```
Traceback (most recent call last):
  File "/home/paperspace/anaconda3/envs/animatediff/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/paperspace/anaconda3/envs/animatediff/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/paperspace/Desktop/AnimateDiff/scripts/animate.py", line 180, in <module>
    main(args)
  File "/home/paperspace/Desktop/AnimateDiff/scripts/animate.py", line 55, in main
    tokenizer    = CLIPTokenizer.from_pretrained(args.pretrained_model_path, subfolder="tokenizer")
  File "/home/paperspace/anaconda3/envs/animatediff/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1760, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/home/paperspace/anaconda3/envs/animatediff/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/paperspace/anaconda3/envs/animatediff/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/paperspace/anaconda3/envs/animatediff/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'models/StableDiffusion/stable-diffusion-v1-5'. Use `repo_type` argument if needed.

```

**Comment by threeal** [comment]
I have experienced this kind of problem before. Make sure that you have placed the Stable Diffusion repository in the correct path.

<img width="388" alt="image" src="https://github.com/guoyww/AnimateDiff/assets/10202888/1f5c226a-b720-40fe-8f92-7ed69bedfb73">

**Comment by NaturalFigurehead** [comment]
> I have experienced this kind of problem before. Make sure that you have placed the Stable Diffusion repository in the correct path.
> 
> <img alt="image" width="388" src="https://user-images.githubusercontent.com/10202888/255782609-1f5c226a-b720-40fe-8f92-7ed69bedfb73.png">

That helped. I was missing the `stable-diffusion-v1-5` part of the path.

Now I'm getting the same error mentioned in #80 though.
