### ISSUE TITLE
Unable to get AnimateDiff to work in my A1111

### ISSUE THREAD

**Issue by JerryOver** [guoyww/AnimateDiff#87]
I had trouble running AnimateDiff. When I have it set to the mm_sd_v15.ckpt model, it will only create one image like it's a normal txt2img generation, but when it's set to mm_sd_v14.ckpt, nothing generates, I get an error message in my cmd window, and my A1111 no longer works right unless I restart it. This is the error message I get in the cmd window when I try to use mm_sd_v14.ckpt with the prompt "cat":

Arguments: ('task(hexftjkar8iuh0m)', 'cat', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', True, 0, 16, 8, 'mm_sd_v15.ckpt', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000249CBE8B0A0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000249CBD88040>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000249CBE8B160>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000249CBE47A60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000249CBE8A560>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000024AFF37AA70>, None, '', 'Get Tags', None, False, '0', 'D:\\AI\\sd.webui\\webui\\models\\roop\\inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, None, False, '0', 'D:\\AI\\sd.webui\\webui\\models\\roop\\inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
Traceback (most recent call last):
  File "D:\AI\sd.webui\webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\AI\sd.webui\webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\AI\sd.webui\webui\modules\txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
  File "D:\AI\sd.webui\webui\modules\processing.py", line 610, in process_images
    res = process_images_inner(p)
  File "D:\AI\sd.webui\webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "D:\AI\sd.webui\webui\modules\processing.py", line 728, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\AI\sd.webui\webui\modules\processing.py", line 976, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\AI\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 383, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\AI\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 257, in launch_sampling
    return func()
  File "D:\AI\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 383, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\AI\sd.webui\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AI\sd.webui\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\AI\sd.webui\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 137, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "D:\AI\sd.webui\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\sd.webui\webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\AI\sd.webui\webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\AI\sd.webui\webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\AI\sd.webui\webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\AI\sd.webui\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\AI\sd.webui\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\sd.webui\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\AI\sd.webui\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\sd.webui\webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 802, in forward
    h = module(h, emb, context)
  File "D:\AI\sd.webui\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 25, in mm_tes_forward
    x = layer(x)
  File "D:\AI\sd.webui\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\sd.webui\webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 109, in forward
    assert x.shape[1] == self.channels
AssertionError

**Comment by welles1123** [comment]
I have exactly same error like yours with A1111 ver 1.3.2, solved after upgrade to ver 1.5.0

**Comment by risjut** [comment]
Had the exact same issue. Fixed it Thanks to welles1123
(moved from version 1.2.x to version 1.5.x)
still the same issue with mm_sd_v15.ckpt but both v14 and v15 now do generate a giff-sequence for me

**Comment by JerryOver** [comment]
Thanks. I haven't done it yet, but thanks for the input. I'll reply back here after I try it.

**Comment by JerryOver** [comment]
>

**Comment by JerryOver** [comment]
I did the git pull thing but still having the same problem. I guess that isn't the way to upgrade to version 1.5.

**Comment by JerryOver** [comment]
I figured it out. I had to use that update.bat. It's working now.
